curso/urls.py
# curso/urls.py

from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
  path('',views.area_view,name='area_url'),
  path('cursos/',views.cursos_view,name='cursos_url'),
  path('curso/<str:curso_nome>/',views.curso_view,name='curso_url'),
  path('disciplina/<str:disciplina_nome>/',views.disciplina_view,name='disciplina_url'),
  path('projeto/<str:projeto_nome>/',views.projeto_view,name='projeto_url'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigo/', include('artigo.urls')),
    path('curso/', include('curso.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('praias/', include('praias.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

curso/models.py
# curso/models.py
from django.db import models

# Create your models here.
class AreaCientifica(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Docente(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome


class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length=200)
    ano = models.PositiveIntegerField()
    semestre = models.PositiveIntegerField()
    ects = models.PositiveIntegerField()
    curricularIUnitReadableCode = models.CharField(max_length=20)
    area_cientifica = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)
    docentes = models.ManyToManyField(Docente)
    linguagens = models.ManyToManyField(LinguagemProgramacao)

    def __str__(self):
        return self.nome


class Projeto(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField()
    conceitos_aplicados = models.TextField()
    tecnologias_utilizadas = models.TextField()
    imagem = models.ImageField(upload_to='projetos/')
    video_link = models.URLField()
    github_link = models.CharField(max_length=200)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    linguagens = models.ManyToManyField(LinguagemProgramacao)

    def __str__(self):
        return self.nome


class Curso(models.Model):
    nome = models.CharField(max_length=200)
    apresentacao = models.TextField()
    objetivos = models.TextField()
    competencias = models.TextField()
    disciplinas = models.ManyToManyField(Disciplina)

    def __str__(self):
        return self.nome

curso/views.py
from django.shortcuts import render
from .models import AreaCientifica, Curso, Disciplina, Projeto

# Create your views here.
def area_view(request):
    areas = AreaCientifica.objects.all().order_by('nome')
    context = {
        'areas': areas,
        }
    return render(request, 'curso/layout.html', context)

def cursos_view(request):
    cursos = Curso.objects.all().order_by('nome')
    context = {
        'cursos': cursos,
    }
    return render(request, 'curso/cursos.html', context)

def curso_view(request, curso_nome):
    curso = Curso.objects.get(nome=curso_nome)
    disciplinas = curso.disciplinas.all()
    context = {
        'curso': curso,
        'disciplinas': disciplinas,
        }
    return render(request, 'curso/curso.html', context)

def disciplina_view(request, disciplina_nome):
    disciplina = Disciplina.objects.get(nome=disciplina_nome)
    projetos = disciplina.projeto_set.all()
    context = {
        'disciplina': disciplina,
        'projetos': projetos,
        }
    return render(request, 'curso/disciplina.html', context)

def projeto_view(request, projeto_nome):
    projeto = Projeto.objects.get(nome=projeto_nome)
    context = {
        'projeto': projeto,
        }
    return render(request, 'curso/projeto.html', context)

curso/templates/curso/curso.html
<!-- curso.html -->
{% extends 'curso/layout.html' %}

{% block content %}
<ul>
        <h1> {{ curso.nome }} </h1>

        <h2>Apresentação: {{ curso.apresentacao }} </h2>

        <h2>Objetivos: {{ curso.objetivos }} </h2>

        <h2>Competências: {{ curso.competencias }} </h2>

        <h2>Lista de disciplinas:
            <ul>
                {% for disciplina in disciplinas %}
                    <li>
                        <a href="{% url 'curso:disciplina_url' disciplina.nome %}">{{ disciplina.nome }}</a>
                    </li>
                {% endfor %}
            </ul>
        </h2>
    </ul>
{% endblock %}

curso/templates/curso/cursos.html
<!-- cursos.html -->
{% extends 'curso/layout.html' %}

{% block content %}
<h1>Lista de Cursos:
    <ul>
        {% for curso in cursos %}
            <li>
                <a href="{% url 'curso:curso_url' curso.nome %}">{{ curso.nome }}</a>
            </li>
        {% endfor %}
    </ul>
</h1>
{% endblock %}

curso/templates/curso/disciplina.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h1> {{ disciplina.nome }} </h1>
    <h2>Ano: {{ disciplina.ano }}</h2>
    <h2>Semestre: {{ disciplina.semestre }}</h2>
    <h2>ECTS: {{ disciplina.ects }}</h2>
    <h2>Código Curricular: {{ disciplina.curricularIUnitReadableCode }}</h2>
    <h2>Área Científica: {{ disciplina.area_cientifica }}</h2>

    <h2>Docentes:
    <ul>
        {% for docente in disciplina.docentes.all %}
            <li>{{ docente.nome }}</li>
        {% endfor %}
    </ul>
    </h2>

    <h2>Linguagens de Programação:
    <ul>
        {% for linguagem in disciplina.linguagens.all %}
            <li>
                {{ linguagem.nome }}
            </li>
        {% endfor %}
    </ul>
    </h2>

    <h2>Projetos:
    <ul>
        {% for projeto in projetos %}
            <li>
                <a href="{% url 'curso:projeto_url' projeto.nome %}">{{ projeto.nome }}</a>
            </li>
        {% endfor %}
    </ul>
    </h2>
{% endblock %}

curso/templates/curso/layout.html
<!-- layout.html -->
<html>
    <head>
        <title>Cursos</title>
        <style>
            body {
                background: magenta;
            }
        </style>
    </head>
<body>
    <header>
    <h1>Áreas Científicas</h1>
    <a href="{% url 'curso:area_url' %}"><button>Área</button></a>
    <ul>
        {% for areaCientifica in areaCientificas %}
            <li>
                {{ areaCientifica.nome }}
            </li>
        {% endfor %}
    </ul>

    <h1>Cursos</h1>
    <a href="{% url 'curso:cursos_url' %}"><button>Cursos</button></a>
    </header>

    <main>
     {% block content %}
     {% endblock %}
    </main>

    {% if user.is_authenticated %}
        <p>Bem-vindo, {{ user.username }}!</p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% else %}
        <a href="{% url 'login' %}"><button>Login</button></a>
    {% endif %}
</body>
</html>

curso/templates/curso/projeto.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h1> {{ projeto.nome }} </h1>
    <img src="{{ projeto.imagem.url }}" alt="Imagem do Projeto">
    <h3>Descrição: {{ projeto.descricao }}</h3>
    <h3>Link para o Vídeo Demonstrativo: <a href="{{ projeto.video_link }}">{{ projeto.video_link }}</a></h3>
    <h3>Conceitos Aplicados: {{ projeto.conceitos_aplicados }}</h3>
    <h3>Tecnologias Utilizadas: {{ projeto.tecnologias_utilizadas }}</h3>
    <h3>Disciplina: {{ projeto.disciplina.nome }}</h3>
    <h3>Linguagens de Programação Utilizadas:</h3>
    <ul>
        {% for linguagem in projeto.linguagens.all %}
            <li>{{ linguagem.nome }}</li>
        {% endfor %}
    </ul>

    <h3>Link para o Repositório GitHub: {{ projeto.github_link }}</h3>
{% endblock %}