bandas/urls.py
# bandas/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'bandas'
urlpatterns = [
  path('', views.layout_view, name='layout_url'),
  path('banda/<str:banda_nome>/',views.banda_view,name='banda_url'),
  path('album/<str:album_nome>/',views.album_view,name='album_url'),
  path('musica/<str:musica_nome>/',views.musica_view,name='musica_url'),
  path('css/',views.css_view,name='css_url')
]

curso/urls.py
# curso/urls.py

from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
  path('',views.area_view,name='area_url'),
  path('cursos/',views.cursos_view,name='cursos_url'),
  path('curso/<str:curso_nome>/',views.curso_view,name='curso_url'),
  path('disciplina/<str:disciplina_nome>/',views.disciplina_view,name='disciplina_url'),
  path('projeto/<str:projeto_nome>/',views.projeto_view,name='projeto_url'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigo/', include('artigo.urls')),
    path('curso/', include('curso.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('praias/', include('praias.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

bandas/models.py
from django.db import models

# Create your models here.
class Banda(models.Model):
    nome = models.CharField(max_length=100)
    foto = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f'{self.nome}'

class Album(models.Model):
    tituloAlbum = models.CharField(max_length=100)
    anoDeLancamento = models.IntegerField()
    capa = models.ImageField(null=True, blank=True)
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.tituloAlbum}'

class Musica(models.Model):
    tituloMusica = models.CharField(max_length=100)
    anoDeLancamento = models.IntegerField()
    link = models.URLField(max_length=200)
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    letra = models.TextField(default='', null=True, blank=True)
    biografia = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return f'{self.tituloMusica}'

bandas/views.py
# bandas/views.py

from django.shortcuts import render
from .models import Banda, Album, Musica

def layout_view(request):
    bandas = Banda.objects.all().order_by('nome')
    context = {
        'bandas': bandas,
    }
    return render(request, 'bandas/layout.html', context)

def banda_view(request, banda_nome):
    banda = Banda.objects.get(nome=banda_nome)
    albuns = banda.album_set.all()
    context = {
        'banda': banda,
        'albuns': albuns,
    }
    return render(request, 'bandas/banda.html', context)

def album_view(request, album_nome):
    album = Album.objects.get(tituloAlbum=album_nome)
    musicas = album.musica_set.all()
    context = {
      'album': album,
      'musicas': musicas,
    }
    return render(request, 'bandas/album.html', context)

def musica_view(request, musica_nome):
   context = {
      'musica': Musica.objects.get(tituloMusica=musica_nome),
   }
   return render(request, 'bandas/musica.html', context)

def css_view(request):
    return render(request, 'bandas/html5-css.html')

bandas/templates/bandas/album.html
<!-- album.html -->
{% extends 'bandas/layout.html' %}

{% block content %}
    <ul>
    <h1> {{ album.banda }} </h1>
    <img src='{{ album.capa.url}}' width="150px">

    <h2> Album: {{ album.tituloAlbum }} - {{ album.anoDeLancamento }} </h2>


    <h2>Lista de músicas do álbum:
    {% for musica in album.musica_set.all %}
       <li> <a href="{% url 'bandas:musica_url' musica.tituloMusica %}">{{ musica }}</a>
       {% if musica.letra %}
            <i class="fa fa-music" title="Esta música tem letra"></i>
       {% endif %}
       </li>
    {% endfor%}
    </h2>
    </ul>
{% endblock %}

bandas/templates/bandas/banda.html
<!-- banda.html -->
{% extends 'bandas/layout.html' %}

{% block content %}
    <ul>
    <h1> {{ banda.nome }} </h1>
    <img src='{{ banda.foto.url}}' width="150px">


    <h2>Lista de álbuns da banda:
    {% for album in banda.album_set.all %}
       <li>
          <a href="{% url 'bandas:album_url' album.tituloAlbum %}">{{ album }}</a>
       </li>

       {% for musica in album.musica_set.all %}
          {% if musica.biografia %}
            <pre>{{ musica.biografia }}</pre>
          {% endif %}
       {% endfor %}
    {% endfor %}
    </h2>
    </ul>
{% endblock %}

bandas/templates/bandas/html5-css.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            background: darkturquoise;
        }
        {% block style %}
        {% endblock %}
    </style>
    <title>Seletores CSS e Combinadores</title>
    <a href="{% url 'bandas:layout_url' %}"><button>Lista</button></a>
</head>
<body>
    <h3>Seletores CSS</h3>
    <p>CSS é utilizado para estilizar páginas web. Ele permite adicionar cores, fontes e layouts às páginas HTML.</p>
    <table>
        <tr>
            <th>Seletores</th>
            <th>Utilizado?</th>
            <th>Comentário</th>
        </tr>
        <tr>
            <td>Seletor de tipo</td>
            <td><img src="used.png" alt="Não Utilizado"></td>
            <td>Seleciona elementos com base no seu tipo (tag). Ainda não utilizei este seletor para aplicar estilos aos parágrafos em um <a href="exemplo.html">exemplo de página</a>.</td>
        </tr>
        <tr>
            <td>Seletor de classe</td>
            <td><img src="not-used.png" alt="Não Utilizado"></td>
            <td>Seleciona elementos com base na sua classe. Ainda não utilizei este seletor em nenhuma página.</td>
        </tr>
        <tr>
            <td>Seletor de ID</td>
            <td><img src="used.png" alt="Não Utilizadoo"></td>
            <td>Seleciona um elemento com base no seu ID único. Ainda não utilizei este seletor para estilizar o cabeçalho de uma <a href="outra_pagina.html">outra página</a>.</td>
        </tr>
    </table>

    <h3>Combinadores de Seletores</h3>
    <table>
        <tr>
            <th>Combinador</th>
            <th>Utilizado?</th>
            <th>Comentário</th>
        </tr>
          <tr>
            <td>Descendente</td>
            <td><img src="used.png" alt="Não Utilizado"></td>
            <td>Seleciona elementos que são descendentes diretos ou indiretos de outro elemento. Ainda não utilizei este combinador em um projeto para estilizar listas dentro de divs.</td>
        </tr>
        <tr>
            <td>Filho direto</td>
            <td><img src="not-used.png" alt="Não Utilizado"></td>
            <td>Ainda não utilizei este combinador em nenhuma página.</td>
        </tr>
</table>
</body>
</html>

bandas/templates/bandas/layout.html
<!-- layout.html -->
<html>
    <head>
        <title>Bandas</title>

        <!-- Carregando static -->
        {% load static %}

        <!-- Link para o CSS -->
        <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">

        <!-- Link para a fonte Google -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

        <!-- Link para o Font Awesome -->
        <script src="https://kit.fontawesome.com/5d1319edfb.js" crossorigin="anonymous"></script>
        <style>
            body {
                background: darkturquoise;
            }
            {% block style %}
            {% endblock %}
        </style>
    </head>
<body>

    <h1>Lista de Bandas</h1>
    <h1>
    <a href="{% url 'bandas:layout_url' %}"><button>Lista</button></a>
    <a href="{% url 'bandas:css_url' %}"><button>CSS</button></a>
    <ul>
        {% for banda in bandas %}
            <li>
                <a href="{% url 'bandas:banda_url' banda.nome %}">{{ banda.nome }}</a>
            </li>
        {% endfor %}
    </ul>
    </h1>

    {% block content %}
    {% endblock %}

    {% if user.is_authenticated %}
        <p>Bem-vindo, {{ user.username }}!</p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% else %}
        <a href="https://a22202461.pythonanywhere.com/admin/login/?next=/admin/bandas/musica/"><button>Login</button></a>
    {% endif %}

</body>
</html>

bandas/templates/bandas/musica.html
<!-- musica.html -->
{% extends 'bandas/layout.html' %}

{% block content %}
    <ul>
        <h1>{{ musica.tituloMusica }}</h1>

        <h2>Lançado em: {{ musica.anoDeLancamento }}</h2>
        <h3>Banda:
        <li><a href="{% url 'bandas:banda_url' musica.banda.nome %}">{{ musica.banda }}</a></li>
        </h3>

        <h3>Álbum:
        <li><a href="{% url 'bandas:album_url' musica.album.tituloAlbum %}">{{ musica.album }}</a></li>
        </h3>

        <h3>Link: <a href="{{ musica.link }}">{{ musica.link }}</a></h3>

        <h3>
        {% if musica.letra %}
        Letra:
        <pre>{{ musica.letra }}</pre>
        {% endif %}
        </h3>
    </ul>
{% endblock %}