curso/urls.py
# curso/urls.py

from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
  path('',views.area_view,name='area_url'),
  path('cursos/',views.cursos_view,name='cursos_url'),
  path('curso/<str:curso_nome>/',views.curso_view,name='curso_url'),
  path('disciplina/<str:disciplina_nome>/',views.disciplina_view,name='disciplina_url'),
  path('projeto/<str:projeto_nome>/',views.projeto_view,name='projeto_url'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigo/', include('artigo.urls')),
    path('curso/', include('curso.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('praias/', include('praias.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

pwsite/urls.py
# pwsite/urls.py

from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'pwsite'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('sobre/', views.sobre_view, name='sobre'),
    path('interesses/', views.interesses_view, name='interesses'),
]

pwsite/models.py
from django.db import models

# Create your models here.

pwsite/views.py
from django.shortcuts import render

# Create your views here.
def index_view(request):
    return render(request, "pwsite/index.html")

def sobre_view(request):
    return render(request, "pwsite/sobre.html")

def interesses_view(request):
    return render(request, "pwsite/interesses.html")

pwsite/templates/pwsite/index.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programação Web</title>
    <style>
        body {
            background: purple;
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <h1>Programação Web</h1>
        <nav>
            <a href="{% url 'pwsite:index' %}">Introducao</a>
            <a href="{% url 'pwsite:sobre' %}">Sobre</a>
            <a href="{% url 'pwsite:interesses' %}">Interesses</a>
        </nav>
    </header>

    <main>
        <h2>Construindo o Futuro da Web</h2>
        <p>Neste curso, exploraremos diversas tecnologias essenciais para o desenvolvimento web moderno:</p>
        <ul>
            <li><strong>Python e Django:</strong> Utilizados para construir aplicações web robustas e escaláveis, para perfecionistas com prazos.</li>
            <li><strong>HTML, CSS e JavaScript:</strong> Essenciais para criar a estrutura, estilo e interatividade das páginas web.</li>
        </ul>
        <p>Vamos mergulhar a fundo nestas tecnologias e aprender a criar experiências incríveis na web!</p>
    </main>

    <footer>
        <p>&copy; 2024 Programação Web, Universidade Lusófona - Todos os direitos reservados.</p>
    </footer>

</body>
</html>

pwsite/templates/pwsite/interesses.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programação Web</title>
</head>
<body>

    <header>
        <h1>Programação Web</h1>
        <nav>
            <a href="{% url 'pwsite:index' %}">Introducao</a>
            <a href="{% url 'pwsite:sobre' %}">Sobre</a>
            <a href="{% url 'pwsite:interesses' %}">Interesses</a>
        </nav>
    </header>

    <main>
      <h2>Aspetos mais interessantes</h2>
      <p>PLACEHOLDER</p>
      <p>BÁ, BÁ</p>

      <h2>Aspetos menos interessantes</h2>
      <p>PLACEHOLDER</p>
      <p>BÉ, BÉ</p>
    </main>

    <footer>
        <p>&copy; 2024 Programação Web, Universidade Lusófona - Todos os direitos reservados.</p>
    </footer>

</body>
</html>

pwsite/templates/pwsite/sobre.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programação Web</title>
</head>
<body>

    <header>
        <h1>Programação Web</h1>
        <nav>
            <a href="{% url 'pwsite:index' %}">Introducao</a>
            <a href="{% url 'pwsite:sobre' %}">Sobre</a>
            <a href="{% url 'pwsite:interesses' %}">Interesses</a>
        </nav>
    </header>

    <main>
      <h2>Descrição</h2>
      <p>A disciplina de Programação Web na Universidade Lusófona é oferecida aos estudantes dos cursos de Engenharia Informática e Informática de Gestão no 2º ano e segundo semestre.</p>
      <p>Neste curso, os alunos mergulham nas tecnologias e conceitos fundamentais para o desenvolvimento de aplicações web modernas e escaláveis.</p>

      <h2>Conteúdo</h2>
      <p>Os alunos aprenderão a utilizar linguagens como HTML, CSS e JavaScript para criar interfaces de usuário interativas e responsivas.</p>
      <p>Também serão introduzidos aos frameworks de desenvolvimento web, como Django, que facilitam a construção de aplicações web robustas e eficientes.</p>

      <h2>Objetivos de Aprendizagem</h2>
      <p>O principal objetivo desta disciplina é capacitar os alunos com as habilidades necessárias para projetar, desenvolver e implantar aplicações web funcionais e esteticamente atraentes.</p>
      <p>Além disso, os alunos serão incentivados a explorar as melhores práticas de desenvolvimento web, bem como a importância da acessibilidade, usabilidade e segurança na criação de websites e aplicações.</p>
    </main>

    <footer>
        <p>&copy; 2024 Programação Web, Universidade Lusófona - Todos os direitos reservados.</p>
    </footer>

</body>
</html>