artigo/urls.py
# artigo/urls.py

from django.urls import path
from . import views

app_name = 'artigo'
urlpatterns = [
  path('',views.artigos_view,name='artigos_url'),
  path('autores/',views.autores_view,name='autores_url'),
  path('artigo/<str:artigo_nome>/',views.artigo_view,name='artigo_url'),
  path('autor/<str:autor_nome>/',views.autor_view,name='autor_url'),
  path('comentario/<int:comentario_id>/',views.comentario_view,name='comentario_url')
]

curso/urls.py
# curso/urls.py

from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
  path('',views.area_view,name='area_url'),
  path('cursos/',views.cursos_view,name='cursos_url'),
  path('curso/<str:curso_nome>/',views.curso_view,name='curso_url'),
  path('disciplina/<str:disciplina_nome>/',views.disciplina_view,name='disciplina_url'),
  path('projeto/<str:projeto_nome>/',views.projeto_view,name='projeto_url'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigo/', include('artigo.urls')),
    path('curso/', include('curso.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('praias/', include('praias.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

artigo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Autor(models.Model):
    nome = models.CharField(max_length=200)
    username = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

class Artigo(models.Model):
    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    conteudo = models.TextField()
    ano_De_Publicacao = models.PositiveIntegerField(default=0)
    ratings_Total = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'"{self.titulo}" | Feito por: {self.autor} | Escrito em: {self.ano_De_Publicacao}'

class Comentario(models.Model):
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    artigo = models.ForeignKey(Artigo, on_delete=models.CASCADE)
    texto = models.TextField()
    ano_Do_Comentario = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Comentário por {self.autor.username} em "{self.artigo.titulo}"'

artigo/views.py
from django.shortcuts import render
from .models import Artigo, Autor, Comentario

# Create your views here.

def artigos_view(request):
    artigos = Artigo.objects.all().order_by('titulo')
    context = {
        'artigos': artigos,
    }
    return render(request, 'artigo/artigos.html', context)

def autores_view(request):
    autores = Autor.objects.all().order_by('nome')
    context = {
        'autores': autores,
    }
    return render(request, 'artigo/autores.html', context)

def autor_view(request, autor_nome):
    autor = Autor.objects.get(nome=autor_nome)
    artigos = autor.artigo_set.all()
    context = {
      'autor': autor,
      'artigos': artigos,
    }
    return render(request, 'artigo/autor.html', context)

def artigo_view(request, artigo_nome):
    artigo = Artigo.objects.get(titulo=artigo_nome)
    comentarios = artigo.comentario_set.all()
    context = {
        'artigo': artigo,
        'comentarios': comentarios,
    }
    return render(request, 'artigo/artigo.html', context)

def comentario_view(request, comentario_id):
   context = {
      'comentario': Comentario.objects.get(id=comentario_id),
   }
   return render(request, 'artigo/comentario.html', context)

artigo/templates/artigo/artigo.html
<!-- artigo.html -->
{% extends 'artigo/layout.html' %}

{% block content %}
    <ul>
    <h1> {{ artigo.titulo }} </h1>


    <h2>Feito por:
    <li><a href="{% url 'artigo:autor_url' artigo.autor.nome %}">{{ artigo.autor }}</a></li>
    </h2>

    <h3>Escrito em: {{ artigo.ano_De_Publicacao }}</h3>
    <h3>Rating: {{ artigo.ratings_Total }}</h3>

    <h2><pre>{{ artigo.conteudo }}</pre></h2>

    <h3>Comentários:
    {% for comentario in artigo.comentario_set.all %}
       <li>
          {{ comentario.autor.username }}: <a href="{% url 'artigo:comentario_url' comentario.id %}">"{{ comentario.texto }}"</a>
       </li>
    {% endfor %}
    </h3>

    </ul>
{% endblock %}

artigo/templates/artigo/artigos.html
<!-- artigos.html -->
{% extends 'artigo/layout.html' %}

{% block content %}
<h1>Lista de Artigos:
    <ul>
        {% for artigo in artigos %}
            <li>
                <a href="{% url 'artigo:artigo_url' artigo.titulo %}">{{ artigo.titulo }}</a>
            </li>
        {% endfor %}
    </ul>
</h1>
{% endblock %}

artigo/templates/artigo/autor.html
<!-- autor.html -->
{% extends 'artigo/layout.html' %}

{% block content %}
    <ul>
        <h1> {{ autor.nome }} </h1>

        <h2>Username: {{ autor.username }} </h2>

        <h2>Lista de artigos do autor:
        {% if autor.artigo_set.all %}
            <ul>
                {% for artigo in autor.artigo_set.all %}
                    <li>
                        <a href="{% url 'artigo:artigo_url' artigo.titulo %}">{{ artigo.titulo }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>  O autor ainda não escreveu nenhum artigo.</h3>
        {% endif %}
        </h2>
    </ul>
{% endblock %}

artigo/templates/artigo/autores.html
<!-- autores.html -->
{% extends 'artigo/layout.html' %}

{% block content %}
<h1>Lista de Autores:
    <ul>
        {% for autor in autores %}
            <li>
                <a href="{% url 'artigo:autor_url' autor.nome %}">{{ autor.nome }}</a>
            </li>
        {% endfor %}
    </ul>
</h1>
{% endblock %}

artigo/templates/artigo/comentario.html
<!-- comentario.html -->
{% extends 'artigo/layout.html' %}

{% block content %}
    <ul>
        <h1>Comentário:</h1>
        <h2>
            "{{ comentario.texto }}"
        </h2>

        <h3>Feito por:
        <li><a href="{% url 'artigo:autor_url' comentario.autor.nome %}">{{ comentario.autor }}</a></li>
        </h3>

        <h3>Escrito em: {{ comentario.ano_Do_Comentario }}</h3>

        <h3>Artigo:
        <li><a href="{% url 'artigo:artigo_url' comentario.artigo.titulo %}">{{ comentario.artigo }}</a></li>
        </h3>

    </ul>
{% endblock %}

artigo/templates/artigo/layout.html
<!-- layout.html -->
<html>
    <head>
        <title>Artigos</title>
        <style>
            body {
                background: #C83F49;
            }
        </style>
    </head>
<body>
    <header>
    <h1>Artigos</h1>
    <a href="{% url 'artigo:artigos_url' %}"><button>Artigos</button></a>
    <a href="{% url 'artigo:autores_url' %}"><button>Autores</button></a>
    </header>

    <main>
     {% block content %}
     {% endblock %}
     {% if user.is_authenticated %}
        <p>Bem-vindo, {{ user.username }}!</p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    <!-- Se o usuário não estiver autenticado, exiba um botão de login -->
    {% else %}
        <a href="{% url 'login' %}"><button>Login</button></a>
    {% endif %}
     </main>
</body>
</html>